name       : klavaro
version    : '3.03'
release    : 3
source     :
    - https://netix.dl.sourceforge.net/project/klavaro/klavaro-3.03.tar.bz2 : e0959f21e54e7f4700042a3a14987a7f8fc898701eab4f721ebcf4559a2c87b5
license    : GPL-3.0-or-later
component  : office
summary    : A very efficient tutor.
description: |
    A touch typing tutor very flexible, supporting customizable keyboard layouts. You can edit and save new or unknown keyboard layouts, as the basic course was designed to not depend on specific ones. Also, there are some charts about the learning process.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
