name       : klavaro
version    : '3.14'
release    : 13
source     :
    - https://ixpeering.dl.sourceforge.net/project/klavaro/klavaro-3.14.tar.bz2 : 87187e49d301c510e6964098cdb612126bf030d2a875fd799eadcad3eae56dab
license    : GPL-3.0-or-later
homepage   : https://klavaro.sourceforge.io
component  : office
summary    : A very efficient touch typing tutor
description: |
    A touch typing tutor very flexible, supporting customizable keyboard layouts. You can edit and save new or unknown keyboard layouts, as the basic course was designed to not depend on specific ones. Also, there are some charts about the learning process.
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtkdatabox)
    - pkgconfig(libcurl)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install DATADIRNAME=share
